"""This script converts an inquiSTR (https://github.com/wdecoster/inquiSTR) "call" output table to the
ExpansionHunter output .json format which is used as a common input format in downstream scripts.

inquiSTR `call` writes a tab-separated table with one row per locus and these columns:

    chromosome  begin  end  info  <sample>_H1  <sample>_H2

The first 4 columns are echoed from the input region BED file (begin/end are 0-based, half-open). The H1 and H2
columns report, for each haplotype, the median length difference from the reference genome in base pairs (positive =
expansion, negative = contraction), or "NaN" when the haplotype could not be genotyped (too few reads, phasing
failure, or a haploid chromosome where H2 is always NaN).

This converter expects the `info` column to contain the locus id in the format "{chrom}-{start_0based}-{end}-{motif}"
(this is how the inquiSTR catalog is generated by the str-truth-set genotyping pipeline). The repeat motif is parsed
from the end of the locus id, and the allele size in repeats is computed as:

    allele_size_bp = (end - begin) + H
    num_repeats    = allele_size_bp // len(motif)

H1/H2 are medians of integer read length differences, so allele_size_bp can be fractional. The repeat count is floored,
matching how the reference repeat count is computed (reference_size_bp // len(motif)), so that a haplotype at exactly
the reference length maps to the same repeat count used for hom-ref detection.
"""

"""
inquiSTR call output example (1 metadata header block, 1 column header line, then 1 row per locus):

# file_type=individual_call
# version=0.27.1
# command=call
# sample=HG002
chromosome	begin	end	info	HG002_H1	HG002_H2
chr1	591733	591751	chr1-591733-591751-A	3	-2
chr1	650383	650423	chr1-650383-650423-AC	0	NaN
"""

"""
ExpansionHunter output format:

  "LocusResults": {
        "chr12-57610122-57610131-GCA": {
          "AlleleCount": 2,
          "LocusId": "chr12-57610122-57610131-GCA",
          "Variants": {
            "chr12-57610122-57610131-GCA": {
              "Genotype": "3/3",
              "GenotypeConfidenceInterval": "3-3/3-3",
              "ReferenceRegion": "chr12:57610122-57610131",
              "RepeatUnit": "GCA",
              "VariantId": "chr12-57610122-57610131-GCA",
              "VariantType": "Repeat"
            }
          }
        },

  "SampleParameters": {
        "SampleId": "HG002",
        "Sex": null
  }
"""


import argparse
import gzip
import math
import re
import simplejson as json
from tqdm import tqdm


def main():
    p = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    p.add_argument("--discard-hom-ref", action="store_true", help="Discard loci where both alleles equal the number "
                   "of repeats in the reference.")
    p.add_argument("--sample-id", help="If not specified, the sample id is parsed from the H1/H2 column names in the "
                   "inquiSTR table header.")
    p.add_argument("--show-progress-bar", action="store_true", help="Show a progress bar")
    p.add_argument("--verbose", action="store_true", help="Print extra info about discarded or no-call loci")
    p.add_argument("inquistr_calls_path", help="inquiSTR call output table path (.inq or .tsv, optionally gzipped)")
    args = p.parse_args()

    print(f"Processing {args.inquistr_calls_path}")
    locus_results = process_inquistr_calls(
        args.inquistr_calls_path,
        sample_id=args.sample_id,
        discard_hom_ref=args.discard_hom_ref,
        show_progress_bar=args.show_progress_bar,
        verbose=args.verbose,
    )

    output_json_path = re.sub("(.inq|.tsv)(.gz)?$", "", args.inquistr_calls_path) + ".json"
    print(f"Writing {len(locus_results['LocusResults']):,d} loci to {output_json_path}")
    with open(output_json_path, "wt") as f:
        json.dump(locus_results, f, indent=3, ignore_nan=True)


def parse_allele_size_in_repeats(median_bp_diff, reference_size_bp, motif_size):
    """Convert an inquiSTR per-haplotype median bp length difference into a number of repeats.

    Args:
        median_bp_diff (str): the H1 or H2 value from the inquiSTR table ("NaN" for no-call).
        reference_size_bp (int): size of the locus in the reference genome (end - begin).
        motif_size (int): length of the repeat motif.

    Returns:
        int or None: the number of repeats, or None if this haplotype is a no-call.
    """
    if median_bp_diff is None or median_bp_diff.strip().lower() in ("nan", "na", "", "."):
        return None
    allele_size_bp = reference_size_bp + float(median_bp_diff)
    if math.isnan(allele_size_bp):
        return None
    return max(0, int(allele_size_bp // motif_size))


def process_inquistr_calls(inquistr_calls_path, sample_id=None, discard_hom_ref=True, show_progress_bar=False,
                           verbose=False):
    locus_results = {
        "LocusResults": {},
        "SampleParameters": {
            "SampleId": sample_id,
            "Sex": None,
        },
    }

    fopen = gzip.open if inquistr_calls_path.endswith("gz") else open

    no_call_count = discarded_hom_ref_count = 0
    with fopen(inquistr_calls_path, "rt") as f:
        if show_progress_bar:
            f = tqdm(f, unit=" inquiSTR rows", unit_scale=True, unit_divisor=1000)

        line_counter = 0
        for line in f:
            if line.startswith("#"):
                continue

            fields = line.rstrip("\n").split("\t")
            if fields[0] == "chromosome":  # column header line
                if sample_id is None and len(fields) >= 5 and fields[4].endswith("_H1"):
                    locus_results["SampleParameters"]["SampleId"] = fields[4][:-len("_H1")]
                    print(f"Got sample id '{locus_results['SampleParameters']['SampleId']}' from the inquiSTR header")
                continue

            line_counter += 1
            try:
                if len(fields) < 6:
                    raise ValueError(f"Expected at least 6 columns, found {len(fields)}")

                chrom, begin, end, locus_id, h1, h2 = fields[0], fields[1], fields[2], fields[3], fields[4], fields[5]
                begin = int(begin)
                end = int(end)

                motif = locus_id.rsplit("-", 1)[-1]
                if not motif or not re.fullmatch("[ACGTN]+", motif):
                    raise ValueError(f"Unable to parse a repeat motif from the end of the locus id '{locus_id}'")
                motif_size = len(motif)

                reference_size_bp = end - begin

                allele_sizes = [
                    parse_allele_size_in_repeats(h1, reference_size_bp, motif_size),
                    parse_allele_size_in_repeats(h2, reference_size_bp, motif_size),
                ]
                # Drop only the no-call (NaN) haplotypes. A locus where exactly one haplotype is NaN is intentionally
                # emitted as a single-allele (haploid) genotype: this is correct both for haploid chromosomes (chrX/chrY
                # in males, where H2 is always NaN) and for autosomal loci that overlap a large deletion on one
                # haplotype, where only the remaining haplotype can be genotyped. The locus is skipped only when both
                # haplotypes are no-calls.
                allele_sizes = [a for a in allele_sizes if a is not None]
                if len(allele_sizes) == 0:
                    no_call_count += 1
                    continue

                allele_sizes.sort()
                num_repeats_in_reference = reference_size_bp // motif_size
                if discard_hom_ref and all(a == num_repeats_in_reference for a in allele_sizes):
                    discarded_hom_ref_count += 1
                    continue

                genotype = "/".join(str(a) for a in allele_sizes)
                genotype_ci = "/".join(f"{a}-{a}" for a in allele_sizes)

                locus_results["LocusResults"][locus_id] = {
                    "AlleleCount": len(allele_sizes),
                    "LocusId": locus_id,
                    "Variants": {
                        locus_id: {
                            "Genotype": genotype,
                            "GenotypeConfidenceInterval": genotype_ci,
                            "ReferenceRegion": f"{chrom}:{begin}-{end}",
                            "RepeatUnit": motif,
                            "VariantId": locus_id,
                            "VariantType": "Repeat",
                        }
                    }
                }
            except Exception as e:
                print(f"Error while parsing inquiSTR record #{line_counter}: {e}")
                print(f"    {line}")

    if verbose or no_call_count or discarded_hom_ref_count:
        print(f"Parsed {len(locus_results['LocusResults']):,d} loci, skipped {no_call_count:,d} no-call loci and "
              f"{discarded_hom_ref_count:,d} hom-ref loci")

    return locus_results


if __name__ == "__main__":
    main()
