"""Converts one or more TR .variants.tsv tables generated by the combine_str_json_to_tsv.py script into a single per-locus TSV table with allele histograms
and outlier sample IDs.

Input format: TSV with columns including LocusId, SampleId, RepeatUnit, and Genotype (one row per sample per locus)

Output format (same as combine_single_sample_LPS_to_allele_histograms.py):

LocusId	Motif	AllAlleleHistogram	ShortAlleleHistogram	HemizygousAlleleHistogram	OutlierSampleIds_AllAlleles	OutlierSampleIds_ShortAlleles	OutlierSampleIds_HemizygousAlleles
"""

import argparse
import collections
import gzip
import json
import os
import sys


def update_histograms(trid, motif, allele, allele_histogram, allele_sample_ids, sample_id, n_outlier_sample_ids):
    histogram = allele_histogram[(trid, motif)]
    sample_ids = allele_sample_ids[(trid, motif)]
    histogram[allele] += 1
    if histogram[allele] <= 2 * n_outlier_sample_ids:  # * 2 since each homozygous sample is counted twice
        if sample_id not in sample_ids[allele]:
            sample_ids[allele].append(sample_id)


def convert_counts_to_histogram_string(allele_counts):
    return ",".join(f"{allele_size}x:{count}" for allele_size, count in sorted(allele_counts.items()))


def convert_sample_ids_to_string(allele_sample_ids, n_outlier_sample_ids=10):
    output_value = []
    output_sample_id_counter = 0
    for allele, sample_list in sorted(allele_sample_ids.items(), key=lambda x: -x[0]):
        if len(sample_list) >= n_outlier_sample_ids:
            break
        for sample_id in sorted(sample_list):
            output_value.append(f"{allele}x:{sample_id}")
            output_sample_id_counter += 1
        if output_sample_id_counter > n_outlier_sample_ids:
            break
    return ",".join(output_value)


def parse_args():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--n-outlier-sample-ids", type=int, default=10,
                    help="Number of samples with the largest alleles to record as outliers (default: %(default)s)")
    p.add_argument("-o", "--output-prefix", help="Output file prefix (default: derived from input filenames)")
    p.add_argument("--trid-list", help="Optional file listing LocusIds (one per line) to include")
    p.add_argument("-n", "--num-rows", type=int, help="Only process the first N data rows per input file")
    p.add_argument("--skip-loci-without-outliers", action="store_true",
                    help="Omit loci that have no outlier sample IDs in any histogram")
    p.add_argument("input_tables", nargs="+", help="Input .variants.tsv(.gz) files")
    return p.parse_args()


def main():
    args = parse_args()

    for path in args.input_tables:
        if not os.path.isfile(path):
            sys.exit(f"Error: {path} not found")

    trids_to_include = None
    if args.trid_list:
        if not os.path.isfile(args.trid_list):
            sys.exit(f"Error: {args.trid_list} not found")
        fopen = gzip.open if args.trid_list.endswith("gz") else open
        with fopen(args.trid_list, "rt") as f:
            trids_to_include = set(line.strip() for line in f if line.strip())
        print(f"Will only include {len(trids_to_include):,d} LocusIds from {args.trid_list}")

    if not args.output_prefix:
        args.output_prefix = f"combined.{len(args.input_tables)}_tables.allele_histograms"

    output_tsv_path = f"{args.output_prefix}.tsv.gz"
    output_json_path = f"{args.output_prefix}.json.gz"

    # Accumulate per-locus histograms and outlier sample IDs
    all_hist = collections.defaultdict(lambda: collections.defaultdict(int))
    all_sample_ids = collections.defaultdict(lambda: collections.defaultdict(list))
    short_hist = collections.defaultdict(lambda: collections.defaultdict(int))
    short_sample_ids = collections.defaultdict(lambda: collections.defaultdict(list))
    hemi_hist = collections.defaultdict(lambda: collections.defaultdict(int))
    hemi_sample_ids = collections.defaultdict(lambda: collections.defaultdict(list))

    for input_path in args.input_tables:
        fopen = gzip.open if input_path.endswith("gz") else open
        with fopen(input_path, "rt") as f:
            header = next(f).rstrip("\n").split("\t")
            for required_col in ("LocusId", "SampleId", "RepeatUnit", "Genotype"):
                if required_col not in header:
                    sys.exit(f"Error: column '{required_col}' not found in {input_path}")
            locus_id_col = header.index("LocusId")
            sample_id_col = header.index("SampleId")
            repeat_unit_col = header.index("RepeatUnit")
            genotype_col = header.index("Genotype")

            print(f"Processing {input_path} ...")
            total_count = 0
            included_count = 0
            for line in f:
                total_count += 1
                if args.num_rows is not None and total_count > args.num_rows:
                    break
                fields = line.rstrip("\n\r").split("\t")
                if len(fields) <= max(locus_id_col, sample_id_col, repeat_unit_col, genotype_col):
                    print(f"  WARNING: skipping line {total_count} with {len(fields)} fields (expected more)")
                    continue

                genotype = fields[genotype_col]
                if not genotype or genotype == ".":
                    continue

                # Skip rows with partial-missing genotypes like "./5" or "5/."
                allele_strings = genotype.split("/")
                if any(a == "." or a == "" for a in allele_strings):
                    continue

                trid = fields[locus_id_col]
                if trids_to_include is not None and trid not in trids_to_include:
                    continue

                included_count += 1
                motif = fields[repeat_unit_col]
                sample_id = fields[sample_id_col]

                alleles = [int(a) for a in allele_strings]
                is_hemizygous = len(alleles) == 1
                short_allele = min(alleles)
                long_allele = max(alleles)

                update_histograms(trid, motif, short_allele, all_hist, all_sample_ids, sample_id, args.n_outlier_sample_ids)
                if not is_hemizygous:
                    update_histograms(trid, motif, long_allele, all_hist, all_sample_ids, sample_id, args.n_outlier_sample_ids)

                update_histograms(trid, motif, short_allele, short_hist, short_sample_ids, sample_id, args.n_outlier_sample_ids)

                if is_hemizygous:
                    update_histograms(trid, motif, short_allele, hemi_hist, hemi_sample_ids, sample_id, args.n_outlier_sample_ids)

        print(f"  Processed {included_count:,d} out of {total_count:,d} rows from {input_path}")

    # Write output
    header = [
        "LocusId", "Motif",
        "AllAlleleHistogram", "ShortAlleleHistogram", "HemizygousAlleleHistogram",
        "OutlierSampleIds_AllAlleles", "OutlierSampleIds_ShortAlleles", "OutlierSampleIds_HemizygousAlleles",
    ]

    print(f"Writing output to {output_tsv_path} ...")
    output_row_counter = 0
    with gzip.open(output_tsv_path, "wt") as out_tsv, gzip.open(output_json_path, "wt") as out_json:
        out_tsv.write("\t".join(header) + "\n")
        out_json.write("[\n")

        for (trid, motif) in sorted(short_hist.keys()):
            all_outliers = convert_sample_ids_to_string(all_sample_ids[(trid, motif)], args.n_outlier_sample_ids)
            short_outliers = convert_sample_ids_to_string(short_sample_ids[(trid, motif)], args.n_outlier_sample_ids)
            hemi_outliers = convert_sample_ids_to_string(hemi_sample_ids[(trid, motif)], args.n_outlier_sample_ids)

            if args.skip_loci_without_outliers and not all_outliers and not short_outliers and not hemi_outliers:
                continue

            # Parse reference region from LocusId (format: <chrom>-<start>-<end>-<motif>)
            trid_parts = trid.split("-")
            if len(trid_parts) != 4:
                sys.exit(f"Error: unexpected LocusId format: {trid}. Expected <chrom>-<start>-<end>-<motif>")
            chrom, start_0based, end, trid_motif = trid_parts
            if not start_0based.isdigit() or not end.isdigit():
                sys.exit(f"Error: unexpected LocusId format: {trid}. Start and end must be integers")

            output_row = {
                "LocusId": trid,
                "ReferenceRegion": f"{chrom}:{start_0based}-{end}",
                "LocusStructure": f"({motif})*",
                "VariantType": "Repeat",
                "Motif": motif,
                "AllAlleleHistogram": convert_counts_to_histogram_string(all_hist[(trid, motif)]),
                "ShortAlleleHistogram": convert_counts_to_histogram_string(short_hist[(trid, motif)]),
                "HemizygousAlleleHistogram": convert_counts_to_histogram_string(hemi_hist[(trid, motif)]),
                "OutlierSampleIds_AllAlleles": all_outliers,
                "OutlierSampleIds_ShortAlleles": short_outliers,
                "OutlierSampleIds_HemizygousAlleles": hemi_outliers,
            }
            out_tsv.write("\t".join(str(output_row[col]) for col in header) + "\n")

            if output_row_counter > 0:
                out_json.write(",\n")
            out_json.write(json.dumps(output_row))
            output_row_counter += 1

        out_json.write("\n]\n")

    print(f"Wrote {output_row_counter:,d} loci to {output_tsv_path} and {output_json_path}")


if __name__ == "__main__":
    main()
